# https://github.com/GATB/bcalm
bcalm_bin_path: /home/ubuntu/Desktop/kurac/bionInf/bcalm/build/bcalm
bcalm_convert_path: /home/ubuntu/Desktop/kurac/bionInf/bcalm/scripts/convertToGFA.py
# https://github.com/pfaucon/PBSIM-PacBio-Simulator
pbsim_bin_path: /home/ubuntu/Desktop/kurac/bionInf/New-folder/PBSIM-PacBio-Simulator/src/pbsim
pbsim_config_path: /home/ubuntu/Desktop/kurac/bionInf/New-folder/PBSIM-PacBio-Simulator/data/model_qc_clr

aligner_bin_path: /home/ubuntu/Desktop/kurac/bionInf/q/GraphAligner/bin/Aligner
